export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'


export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCTS_REQUEST'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCTS_SUCCESS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCTS_FAIL'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'