export const DAILYREPORT_LIST_REQUEST = 'DAILYREPORT_LIST_REQUEST'
export const DAILYREPORT_LIST_SUCCESS = 'DAILYREPORT_LIST_SUCCESS'
export const DAILYREPORT_LIST_FAIL = 'DAILYREPORT_LIST_FAIL'


export const DAILYREPORT_ADD_REQUEST = 'DAILYREPORT_ADD_REQUEST'
export const DAILYREPORT_ADD_SUCCESS = 'DAILYREPORT_ADD_SUCCESS'
export const DAILYREPORT_ADD_FAIL = 'DAILYREPORT_ADD_FAIL'