export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST'
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS'
export const TRANSACTIONS_FAIL = 'TRANSACTIONS_FAIL'

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST'
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS'
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL'

export const TRANSACTION_ADD_REQUEST = 'TRANSACTION_ADD_REQUEST'
export const TRANSACTION_ADD_SUCCESS = 'TRANSACTION_ADD_SUCCESS'
export const TRANSACTION_ADD_FAIL = 'TRANSACTION_ADD_FAIL'
export const TRANSACTION_ADD_RESET = 'TRANSACTION_ADD_RESET'

export const TRANSACTION_DELETE_REQUEST = 'TRANSACTION_DELETE_REQUEST'
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS'
export const TRANSACTION_DELETE_FAIL = 'TRANSACTION_DELETE_FAIL'
